[build]
  publish = "dist"
  command = "npm run build"

# Gestion SPA React (redirection pour éviter les erreurs 404 au rafraîchissement)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200